kumuluzee:
  name: price-updater-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/PriceUpdaterDS
      connection-url: jdbc:postgresql://host.docker.internal:5432/price-updater
      username: dbuser
      password: postgres
      max-pool-size: 20
  dev:
    scan-libraries:
      - price-updater-lib
  openapi-mp:
    enabled: true
    ui:
      enabled: true
      mapping: /openapi/ui
  config:
    consul:
      agent: http://host.docker.internal:8500
  metrics:
    servlet:
      enabled: true
      mapping: /metrics
    web-instrumentation:
      - name: item-endpoint
        url-pattern: /v1/item/*
        status-codes: "200, 404, 500"
      - name: store-endpoint
        url-pattern: /v1/store/*
        status-codes: "200, 404, 500"
      - name: request-endpoint
        url-pattern: /v1/request/*
        status-codes: "200, 202, 404, 500"
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                      <Configuration name="comments">
                          <Appenders>
                              <Console name="console" target="SYSTEM_OUT">
                                  <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                              </Console>
                              <Socket name="logstash" host="3a68956d-0567-4cd2-8ad3-bfda5f432292-ls.logit.io" port="23732" protocol="udp">
                                  <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                              </Socket>
                          </Appenders>
                          <Loggers>
                              <!-- Default logger -->
                              <Logger name="mtn.rso.pricecompare.priceupdater" level="trace"/>
                              <Root level="info">
                                  <AppenderRef ref="console" level="trace" />
                                  <AppenderRef ref="logstash" level="trace" />
                              </Root>
                          </Loggers>
                      </Configuration>'

api-properties:
  return-all-item-prices: true
  return-all-store-prices: true

update-processing-properties:
  request-retention-period: 604800
  price-retention-period: 604800
  data-source: 1
  update-prices-tus: true
  update-prices-mercator: true
  update-prices-spar: true
