kumuluzee:
  name: price-updater-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/PriceUpdaterDS
      connection-url: jdbc:postgresql://host.docker.internal:5432/price-updater
      username: dbuser
      password: postgres
      max-pool-size: 20
  dev:
    scan-libraries:
      - price-updater-lib
  openapi-mp:
    enabled: true
    ui:
      enabled: true
      mapping: /openapi/ui
  metrics:
    servlet:
      enabled: true
      mapping: /metrics
    web-instrumentation:
      - name: item-endpoint
        url-pattern: /v1/item/*
        status-codes: "200, 404, 500"
      - name: store-endpoint
        url-pattern: /v1/store/*
        status-codes: "200, 404, 500"
      - name: request-endpoint
        url-pattern: /v1/request/*
        status-codes: "200, 202, 404, 500"
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                      <Configuration name="comments">
                          <Appenders>
                              <Console name="console" target="SYSTEM_OUT">
                                  <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                              </Console>
                          </Appenders>
                          <Loggers>
                              <!-- Default logger -->
                              <Logger name="mtn.rso.pricecompare.priceupdater" level="TRACE"/>
                              <Root level="info">
                                  <AppenderRef ref="console" level="trace" />
                                  <AppenderRef ref="logstash" level="trace" />
                              </Root>
                          </Loggers>
                      </Configuration>'
