global:
  scrape_interval: 5s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'price-updater-metrics'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8080']
